### ISSUE TITLE
HERB working wirelessly

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/block_sorting#1]
Get HERB to work wirelessly.

**Comment by ClintLiddick** [comment]
Just to clarify, does this mean working outside the lab demo, or with no cable connecting it to a laptop/controlling computer?

**Comment by siddhss5** [comment]
Up to you to figure this out :).

**Comment by mkoval** [comment]
@ClintLiddick Can we connect an external monitor on `herb2` for visualization? I recall having issues with the video outputs on that graphics card.

**Comment by ClintLiddick** [comment]
@mkoval yes we definitely can and have. The only problem is sometimes it needs to be restarted before it'll recognize it's been plugged int.
