### ISSUE TITLE
Always reports "failed to grab block" in simulation

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/block_sorting#10]
I get this error every time I run the demo in simulation:

```
[ERROR] [block_sorting:run_demo.py:140]:<module>: Failed to grasp the block
```

@Stefanos19 Could this be related to your grasp verification code?

**Comment by mkoval** [comment]
@jeking04 I think you mentioned that you fixed this?

**Comment by jeking04** [comment]
I added logic to always return true in VerifyGrasp when in simulation mode:

https://github.com/personalrobotics/block_sorting/blob/master/src/block_sorting/block_utils.py#L102

I think this was the issue.
